D3/EDAV3Notes.md
in Binding Data (console) section
=> Fixed syntax error

D3/ExerciseSolutions.md
=> Update ExerciseSolutions.md with EDAV2 solutions

D3/ExerciseSolutions.md
=> Update ExerciseSolutions.md with EDAV3 solutions.

D3/ExerciseSolutions.md
Added EDAV3 solutions with data binding.
=> Update ExerciseSolutions.md with EDAV3 solutions with data binding.

D3/ExerciseSolutions.md
Added EDAV3 solutions with appending using data.
=> Update ExerciseSolutions.md with EDAV3 solutions with appending using data.

D3/ExerciseSolutions.md
Trying out fork/update on github
=> Adding Solution of EDAV3 practice

D3/ExerciseSolutions.md
Updating solutions page for EDAV2
=> Updated EDAV2

D3/ExerciseSolutions.md
Delays were not working after Step 4 , so tried them on console, used block comment in script section
=> Adding solution to EDAV4

D3/EDAV7_3_obj_constancy.html
that's the point of creating exitpos, right?
=> replacing `w` with `exitpos` in update(bardata,w)

collaborate.Rmd
Fixes # .
Changed proposed in this pull request:
-
-
-
=> Fixed typo

basics.Rmd
=> add R for Data Science and DataCamp

general_resources.Rmd
Added NY Open Statistical programming meetup as a resource. I have only been to one talk, on gestalt last month, but it was enjoyable and there are videos of talks available online.
=> Adding R Meetup

histogram.Rmd
Made some changes on a new branch
=> Change subtitles, minor edits

final_presentation.Rmd
Switched Travis back on to build new branches and pull requests.
Built branch successfully (before pull request was initiated) and it did not affect gh-pages or master. No change seen on live site. Yay!
=> Testing Travis Automation

final_presentation.Rmd
Okay. Try this again. Now switched off pull request builds.
=> Travis revert, new settings

basics.Rmd
Seeing if Travis ignores this build.
=> testing pull request setup

basics.Rmd
See new first bullet point in R Markdown and Knitr section. Also explained the difference between R Markdown and Knitr.
=> Add link to R Markdown intro

heatmap.Rmd
Other types of heat maps still need to be added. Click to download: [heatmaps.html](https://courseworks2.columbia.edu/files/3433924/download?download_frd=1 )
(Requires CourseWorks access)
=> Clarify that these are 2d bin heat maps

final_presentation.Rmd
Still not clear whether it's ok to make edits to files like this (with no code) directly to master.  Therefore erring on the side of caution and creating a new branch.
=> updates / edits

final_presentation.Rmd
Apparently {target="_blank"} doesn't work with spaces around the =.
=> Fix CDC link

DESCRIPTION
There was a problem in DESCRIPTION. Maybe that's it.  I don't like that GitHub is merging the pull requests before the Travis check has passed... was it always working that way?
=> missing comma

.travis.yml, DESCRIPTION, _bookdown.yml
Hookup packages and try to run on Travis
=> maps chapter

.travis.yml, chapter_index.Rmd, maps.Rmd
Add maps to chapter index and minor tweaks
=> General update

bargraph.Rmd
and change chapter title to Bar Chart
=> Add link to reordering bars tutorial

perception.Rmd
Originally incorrectly linked to The Elements of Graphing Data
=> Fixed a book link

general_resources.Rmd
=> Add Twitter Section to General Resources

index.Rmd
Here's a simple addition. Hope you like it...
=> Testing PR setup

contributors.csv, index.Rmd
- Run contributors script to update new student contributors (added to intro automatically just by rerunning script to update CSV)
- Add icon/design colophon on main page (general info on icons/where to access/how to attribute)
=> update contributors and add design colophon

contribute.Rmd, import_data.Rmd, workflow_notes.Rmd
Updated workflow_notes, contribute, and import_data
=> Test branch

final_presentation.Rmd
teams of 2
updates to outline, # of pages
grading criteria
=> update for Spring 2019
